spring:
  application:
    name: problem-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/problem_service_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false}
    username: ${SPRING_DATASOURCE_USERNAME:problemuser}
    password: ${SPRING_DATASOURCE_PASSWORD:problempass123}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  
  # OAuth2 Resource Server Configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8321/realms/online-judge}

server:
  port: ${SERVER_PORT:8080}

eureka:
  client:
    enabled: ${EUREKA_CLIENT_ENABLED:true}
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

logging:
  level:
    org.springframework.security: INFO
